### ISSUE TITLE
Version should be 0.1, or found/generated from https://github.com/Phenomics/ontolib

### ISSUE THREAD

**Issue by johntiger1** [Phenomics/ontolib#10]
Ex. I am working on a project with version and it was not working. 
<version>1.0-SNAPSHOT</version>

```
<dependencies>
  <dependency>
    <groupId>com.github.phenomics</groupId>
    <artifactId>ontolib-core</artifactId>
    <version>${project.version}</version>
  </dependency>
  <dependency>
    <groupId>com.github.phenomics</groupId>
    <artifactId>ontolib-io</artifactId>
    <version>${project.version}</version>
  </dependency>
</dependencies>
```

**Comment by holtgrewe** [comment]
I am not quite sure I understand? Can you show me a minimal working example where this breaks?

**Comment by johntiger1** [comment]
Sure, the example is from my project actually: https://github.com/johntiger1/boqa/blob/master/pom.xml

I had to change around the 82nd line to get it to work

**Comment by holtgrewe** [comment]
I don't quite understand.

You should be able to build with Ontolib as dependency directly from maven central with the non snapshot versions. If you want to install the snapshot/development versions you simply do mvn install on your dependency and the you can build your project...

**Comment by johntiger1** [comment]
If you set project.version elsewhere in your project, won't it be different from the project.version of Ontolib?

**Comment by holtgrewe** [comment]
This setting is local to the ontolib parent pom.xml and all included pom.xml files afaik.
