### ISSUE TITLE
SLF4J messages

### ISSUE THREAD

**Issue by pnrobinson** [Phenomics/ontolib#16]
Hi
I am using log4j in my application code and yet I am getting these messages from SLF4J. This is undesired behavior for library code.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/peter/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.5/log4j-slf4j-impl-2.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/peter/.m2/repository/org/slf4j/slf4j-log4j12/1.7.24/slf4j-log4j12-1.7.24.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/peter/.m2/repository/com/github/phenomics/ontolib-cli/0.2/ontolib-cli-0.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

**Comment by pnrobinson** [comment]
Sorry, this was a bug in my pom file.

**Comment by holtgrewe** [comment]
Actually it is bug in v0.2 but fixed in develop. Will release 0.3 on Monday.

**Comment by holtgrewe** [comment]
Fixed in #19.
