### ISSUE TITLE
Xrefs

### ISSUE THREAD

**Issue by pnrobinson** [Phenomics/ontolib#17]
Is there is method to retrieve cross refs? I could not find anything like this in the Term class

**Comment by holtgrewe** [comment]
Agreed, is parsed but not made available in `Term`.

**Comment by holtgrewe** [comment]
@pnrobinson Can you try whether this works for you? You can get the current `develop` branch and do `mvn install`. When then depending on the `0.3-SNAPSHOT` version, you have the installed development version available in your project.

**Comment by holtgrewe** [comment]
@pnrobinson I just release v0.3 with this feature. It should be on maven central soon.
