### ISSUE TITLE
HpoID vs TermID

### ISSUE THREAD

**Issue by johntiger1** [Phenomics/ontolib#24]
What is the difference between the two? They appear to do the same thing in HpoDiseaseAnnotation.java

**Comment by cmungall** [comment]
We're also wondering the same thing. I'd like to use ontolib across a wider set of ontologies, it's not scalable to keep adding in new seemingly identical implementations.

This also applies to the `Term` interface and `HpoTerm` etc.

**Comment by cmungall** [comment]
Also all the implementations of `TermRelation`. And what is `VegetableTermRelation`

**Comment by iamkoehler** [comment]
@holtgrewe we should have another session. I think there might be better designs here.

**Comment by iamkoehler** [comment]
@johntiger1  `TermID` is probably from ontologizer. 

We will discuss the other design issue offline and via email with @cmungall and others.
