### ISSUE TITLE
TermID vs TermId

### ISSUE THREAD

**Issue by johntiger1** [Phenomics/ontolib#25]
Would it be possible to provide an adapter perhaps? Also, for curiosity's sake, what was the reason for moving from TermID to TermId? Thanks!

**Comment by johntiger1** [comment]
For example, right now I have something like this:
TermID t = new TermID(anno.getTermId().getIdWithPrefix());

**Comment by holtgrewe** [comment]
Hi, what `TermID` are you referring to?

We moved from `TermID` to `TermId` to adhere to the Google Java Code Style.

**Comment by iamkoehler** [comment]
I also don't see any `TermID` in ontolib. I will close this. Let me know if you still think this is an ontolib-issue.

Wild guess: you are still importing `TermID` from ontologizer somewhere.
