### ISSUE TITLE
Maven Central version badge

### ISSUE THREAD

**Issue by julesjacobsen** [Phenomics/ontolib#27]
Can you add one of these for the project please - saves me having to check the releases page to see what the latest released version is, plus you don't need to update your README.md each time.

[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.github.phenomics/ontolib-core/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.github.phenomics/ontolib-core)

**Comment by holtgrewe** [comment]
Thanks!
